### ISSUE TITLE
URGENT!!! ASAP!!!!! LAUNCH BLOCKER!!!! Converted doesn't convert for design paths

### ISSUE THREAD

**Issue by yvoronoy** [isitnikov/m2-convert-patch-for-composer-install#3]
@isitnikov Paths like app/design doesn't work.
FIX IT ASAP, URGENT ISSUE!!!!!!!!!! LAUNCH BLOCKER! @isitnikov 
![FIX](http://risovach.ru/upload/2017/03/mem/mudriy-paca_141388470_orig_.jpg)

Thank you man

**Comment by isitnikov** [comment]
Fixed afd9c57

**Comment by yvoronoy** [comment]
@isitnikov thank you :1st_place_medal:
